name: anand_yogalaya
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: 2.1.0
  flutter_staggered_grid_view: ^0.4.0
  provider: ^5.0.0
  flushbar: ^1.10.4
  flutter_slidable: ^0.6.0
  lottie: ^1.2.1
  flutter_icons: ^1.1.0
  get: ^4.6.1
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  google_sign_in: ^5.2.3
  cloud_firestore: ^3.1.8
  cached_network_image: ^3.2.0
  flutter_inappwebview: ^5.3.2
  carousel_slider: ^4.0.0
  like_button: ^2.0.4
  shimmer: ^2.0.0
  flutter_network_connectivity: ^0.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
